//1. create a promise that resolves with a message after a 2-sec timeout and log the message to the console.

//2. create a promise that rejects with an error message after a 2-second timeout and handle the error using '.catch()' .

